# Generated by Django 5.1.4 on 2024-12-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
