# Generated by Django 5.1.4 on 2025-02-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(default='Default Team', max_length=100),
        ),
    ]
