# Generated by Django 5.1.3 on 2024-11-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blogpost_read_access"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="edit_access",
            new_name="post_permissions",
        ),
    ]
