# Generated by Django 5.1.4 on 2025-02-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpost_post_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='public',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_public',
            field=models.CharField(choices=[('none', 'None'), ('read only', 'Read Only')], default='read only', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='owner',
            field=models.CharField(choices=[('read and edit', 'Read and Edit')], default='read and edit', max_length=20),
        ),
    ]
